InviteLength: 15
#SWITCHER custom item
SWITCHER:
  Material: SNOWBALL
  DisplayName: "&6&lSwitcher Snowball"
  Lore:
    - "&7Hit a player within &67"
    - "&7blocks to switch with them."
  #Maximum distance the snowball will work over, set to -1 if infinite
  MaxDistance: -1
  #Ability cooldown usage should give
  Cooldown: 15
  #Whether the item should have an enchant glint
  Enchanted: true

#TIMEWARP_PEARL custom item
TIMEWARP_PEARL:
  Material: ENDER_PEARL
  DisplayName: "&5&lTimewarp Pearl"
  Lore:
    - "&7Throw this pearl and be"
    - "&7teleported back to your throw"
    - "&7point after &615 &7seconds"
  #Ability cooldown usage should give (in seconds)
  Cooldown: 30
  #Delay between throwing and warp (in seconds)
  WarpDelay: 15
  #Whether the item should have an enchant glint
  Enchanted: true
CORRUPTED_PEARL:
  Material: ENDER_PEARL
  DisplayName: "&5&lTimewarp Pearl"
  Lore:
    - "&7Throw this pearl and be"
    - "&7teleported back to your throw"
    - "&7point after &615 &7seconds"
  Cooldown: 30
  Enchanted: false
SPIRIT_LINK:
  Material: IRON_INGOT
  DisplayName: "&b&lSpirit Link"
  Lore:
    - "&7Right click any player to"
    - "&7link your soul to theirs"
    - "&7and receive a buff while near them"
  Cooldown: 30
  Enchanted: true
  MaxDistance: 30D

