#SNOWBALL custom item
SNOWBALL:
  Material: SNOWBALL
  DisplayName: "&6&lSnowball"
  Lore:
    - "&7Hit a player within 7"
    - "&7blocks to switch with them."
  #Maximum distance the snowball will work over, set to -1 if infinite
  MaxDistance: -1
  #Ability cooldown usage should give
  Cooldown: 15
  #Whether the item should have an enchant glint
  Enchanted: true