name: CustomItems
main: me.poilet66.customitems.CustomItems
version: 1.0.0
api-version: 1.16
author: poilet66
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, PlayerParticles, WorldGuard]

commands:
  giveitem:
    usage: /giveitem <id>
    description: give user a custom item
  cireload:
    usage: /cireload
    description: reload config
  ciinvite:
    usage: /ciinvite
    description: accept/deny a request item invite